# config/packages/easy_admin.yaml

easy_admin:
    design:
        menu:
            - { label: 'Dashboard', icon: 'fa fa-dashboard', route: 'easyadmin' }
            - { label: 'Tâches', icon: 'fa fa-tasks', route: 'easyadmin', routeParameters: { entity: 'Tache' } }
    user:
        display_name: true
        name_property_path: 'username'
    entities:
        User:
            class: App\Entity\User
        Contrat:
            class: App\Entity\Contrat
        Document:
            class: App\Entity\Document
        Tache:
            class: App\Entity\Tache
            controller: App\Controller\Admin\TacheCrudController
