# config/packages/easy_admin.yaml
easy_admin:
    design:
        templates:
            layout: '@EasyAdmin/crud/base.html.twig' # Spécifiez le chemin du template de base
    menu:
        - { label: 'Dashboard', icon: 'fa fa-dashboard', route: 'admin_dashboard' }
        - { label: 'Calendrier', icon: 'fa fa-calendar', route: 'calendrier_dashboard' }
    entities:
        User:
            class: App\Entity\User
        Contrat:
            class: App\Entity\Contrat
        Document:
            class: App\Entity\Document
        Tache:
            class: App\Entity\Tache
        Calendrier:
            class: App\Entity\Calendrier
            controller: App\Controller\CalendrierController1
