# config/packages/security.yaml
security:
    enable_authenticator_manager: true

    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        main:
            lazy: true
            provider: user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: admin_dashboard 
            logout:
                path: app_logout
                target: /

    access_control:
        # Accès à /admin limité aux utilisateurs avec ROLE_USER
        - { path: ^/admin, roles: ROLE_USER }

