vich_uploader:
    db_driver: orm
    mappings:
        contract_file:
            uri_prefix: /files/contracts
            upload_destination: '%kernel.project_dir%/public/files/contracts'
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
