parameters:
    upload_directory: '%kernel.project_dir%/public/uploads/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Autoload all services in the src/ directory, except the ones excluded
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Autoload controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
