services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    # Autoload all services in the src/ directory, except the ones excluded
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Autoload controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Define your custom service explicitly
    App\Service\GoogleCalendarService:
        # Optionally, if needed, define arguments here
        # arguments:
        #     $googleApiKey: '%env(GOOGLE_API_KEY)%'
