services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Autoload all services in the src/ directory, except the ones excluded
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Autoload controllers
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Define Google_Client service using the configurator class
   # App\Service\GoogleClientConfigurator:
       # public: true

  #  Google_Client:
        #class: Google_Client
       # factory: ['@App\Service\GoogleClientConfigurator', 'createClient']

    # Define Google Calendar Service
    #App\Service\GoogleCalendarService:
        #arguments:
           # - '@Google_Client'
